"""initial migration

Revision ID: ea56edd686c9
Revises:
Create Date: 2026-08-02 23:42:50.694295

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ea56edd686c9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column(
            "import_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("rows_imported", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_logs")),
    )
    op.create_table(
        "lottery_draws",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("draw_date", sa.Date(), nullable=False),
        sa.Column("government_round", sa.String(length=50), nullable=True),
        sa.Column("first_prize", sa.String(length=6), nullable=False),
        sa.Column("last_two", sa.String(length=2), nullable=True),
        sa.Column("front_three", sa.String(length=3), nullable=True),
        sa.Column("back_three", sa.String(length=3), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lottery_draws")),
    )
    op.create_index(op.f("ix_lottery_draws_draw_date"), "lottery_draws", ["draw_date"], unique=True)
    op.create_table(
        "lottery_number_statistics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sa.String(length=6), nullable=False),
        sa.Column("frequency", sa.Integer(), nullable=False),
        sa.Column("last_seen", sa.Date(), nullable=True),
        sa.Column("hot_score", sa.Float(), nullable=False),
        sa.Column("cold_score", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lottery_number_statistics")),
    )
    op.create_index(
        op.f("ix_lottery_number_statistics_number"),
        "lottery_number_statistics",
        ["number"],
        unique=True,
    )
    op.create_table(
        "prediction_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prediction_date", sa.Date(), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("predicted_numbers", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("actual_result", sa.String(length=6), nullable=True),
        sa.Column("accuracy", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prediction_history")),
    )
    op.create_index(
        op.f("ix_prediction_history_prediction_date"),
        "prediction_history",
        ["prediction_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prediction_history_prediction_date"), table_name="prediction_history")
    op.drop_table("prediction_history")
    op.drop_index(
        op.f("ix_lottery_number_statistics_number"), table_name="lottery_number_statistics"
    )
    op.drop_table("lottery_number_statistics")
    op.drop_index(op.f("ix_lottery_draws_draw_date"), table_name="lottery_draws")
    op.drop_table("lottery_draws")
    op.drop_table("import_logs")
    # ### end Alembic commands ###
